name: builder
description: Compiles dart code to an AOT bundle, also syncs config files accordingly
version: 1.0.0
homepage: 'https://github.com/therenca/builder'
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
 yaml: ^3.1.0
 leo:
  path: ../../leo
 dcli: ^1.30.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.0
