name: builder
description: Compiles dart code to an AOT bundle, also syncs config files accordingly
version: 1.0.0
author: Therenca Mureithi <therencamureithi@gmail.com>
homepage: 'https://github.com/therenca/builder'

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
 yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
